services:
    observium-api:
        build: .
        command: sh -c "yarn dev"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - "8080:8080"
            - "8081:8081"
        profiles:
            - api
        env_file:
            - ./.env

    observium-db:
        image: postgres:15-alpine
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_DB}
        ports:
            - "${DATABASE_PORT}:5432"
        env_file:
            - ./.env

volumes:
    node_modules:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${PWD}/node_modules
