services:
    observium-db:
        image: postgres:15-alpine
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        env_file:
            - ./.env
