services:
    observium-db:
        image: postgres:15-alpine
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_DB}
        ports:
            - "${DATABASE_PORT}:5432"
        env_file:
            - ./.env
